name: acceptance tests

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'develop'
      - 'add_info_to_slack'

jobs:
  run-acceptance-tests:
    name: Run acceptance tests
    runs-on: ubuntu-latest
    steps:
      - name: Slack notification on failure
        uses: ravsamhq/notify-slack-action@v1
        if: always()
        with:
          status: ${{ job.status }}
          notification_title: 'Mizu {workflow} has {status_message}'
          message_format: '{emoji} *{workflow}* {status_message} during <{run_url}|run>, after commit <<https://github.com/up9inc/mizu/commit/b47718e|b47718e TRA-4442 Improve UI performance (#960)${{ github.event.head_commit.committer.email }}>'
          footer: 'Linked Repo <{repo_url}|{repo}>'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
